### ISSUE TITLE
MCU Error

### ISSUE THREAD

**Issue by Badghostuk** [billkenney/update_max3_plus3#10]
Hi I went through all the setup and got everything setup , I found that at the sudo mount /dev/sda1 /mnt through up an error that /dev/sda1 couldn’t be found I did do the process a number of times and if it came up with this restarted and then trying to press the Button for 2 minutes before trying again.

tried a few times and it didn’t work but proceeding with the rest of the setup worked fine. After booting from the last section before Install Web Cam and WiFi Fix.

Fluid came up fine well as far as I could see, I then backed up the EMMC to another EMMC so I had a fresh installed system to revert back to I then put the cloned EMMC into printer and when I booted I am getting this :

<><><><><><><><><><><><><><><><><><><><>

MCU Protocol error

This is frequently caused by running an older version of the
firmware on the MCU(s). Fix by recompiling and flashing the
firmware.

Your Klipper version is: v0.12.0-317-gb89d55238-dirty
MCU(s) which should be updated:
mcu: Current version v0.12.0-175-g7b490f3e
MKS_THR: Current version v0.10.0-530-g3387a9c2-dirty-20221210_215217-mkspi
Up-to-date MCU(s):

Once the underlying issue is corrected, use the "RESTART"
command to reload the config and restart the host software.

mcu 'MKS_THR': Command format mismatch: query_adxl345 oid=%c rest_ticks=%u vs query_adxl345 oid=%c clock=%u rest_ticks=%u

<><><><><><><><><><><><><><><><><><><><>

When I kicked off the Command to flash the PrintHead it progressed through with no errors despite the amount issue previous. 

Thankyou for doing such a fantastic job on this if I can finally get SpoolMan working etc I have to get a link for BuyMe a Coffee there is no way this took you five minutes and the attention to detail is amazing.

**Comment by billkenney** [comment]
So you were able to get the MCU flashed and everything is working?

**Comment by Badghostuk** [comment]
![IMG_6450](https://github.com/user-attachments/assets/b3e84073-0bed-446f-a08f-9f6ed1e3832c)
Hi it starts up then locks out after a minute or so, managed to get the PrintHead Flashed and followed everything else, I have the BTT MicroProbe

**Comment by Badghostuk** [comment]
[printercfg.txt](https://github.com/user-attachments/files/17347055/printercfg.txt)
[probecfg.txt](https://github.com/user-attachments/files/17347056/probecfg.txt)

These are my Printer cfg and probe cfg

**Comment by Badghostuk** [comment]
![Uploading IMG_5766.png…]()

**Comment by billkenney** [comment]
I don't know anything about the BTT microprobe. I'm assuming you followed BTT's instructions (or a guide) to get it configured?

**Comment by Badghostuk** [comment]
Yes would you mind looking at my probe section I don’t know whether I’ve messed it up due to changing that incorrectly, would very much appreciate it Sent from my iPhoneOn 11 Oct 2024, at 21:22, billkenney ***@***.***> wrote:﻿
I don't know anything about the BTT microprobe. I'm assuming you followed BTT's instructions (or a guide) to get it configured?

**Comment by billkenney** [comment]
Try adding z_offset to probecfg. This is from the btt manual:
[probe]
pin: ^PC13 # The detection IO on the SKR 3 is PC13, V1 should be ^PC13 means high-level triggered, V2 should be ^!PC13 means low -level triggered.
deactivate_on_each_sample: False
x_offset: 0.0 # Actual installed offset of MicroProbe
y_offset: 0.0 # Actual installed offset of MicroProbe
z_offset: 0.0 # Actual installed offset of MicroProbe
speed: 5.0
activate_gcode:
    Probe_Deploy
    G4 P500 # Allow 500 milliseconds for the probe to deploy
deactivate_gcode:
    Probe_Stow

There are spaces in front of Probe_Deploy, G4 P500, and Probe_Stow, but they don't appear on this comment for some reason

**Comment by Badghostuk** [comment]
Hi thankyou sorry I have been in hospital but yes I managed to add the probe details Sent from my iPadOn 15 Oct 2024, at 23:22, billkenney ***@***.***> wrote:﻿
Closed #10 as completed.
