### ISSUE TITLE
Z-Offset?

### ISSUE THREAD

**Issue by drewp29** [billkenney/update_max3_plus3#11]
First off, thank you so much for the extensive guide! I followed everything and after working through a few hiccups, I have my Xmax3 up and running. I did have to install a different Wifi dongle, but I think the Tenda that came with the printer may in fact be dead as I tried it on my girlfriend's laptop last night and couldn't get it to recognize as anything but a mass storage device (whatever a 3MB 'mass' storage would be anyway, lol). I had an extra TP-Link Wifi 6E dongle laying around it worked just fine without having to install a driver.

Anywho, on to the issue at hand - After getting everything back up and running I am wondering how the Z-offset works now. I am using a Cartographer probe for ABL, and after setting it up and tuning for temperature drift, I set the default Z-offset using probe_calibrate. This is pretty close to the proper Z-offset for printing ASA, but does need some tweaking to get perfect squish. I ran the Z-offset calibration from the printer's screen like normal, but it does not seem to actually store the change?

Qidi had changed the Z-offset in one of their firmware updates so that when running the calibration it always starts at 0.00mm, and I figured that was what was happening when I ran the offset calibration after setting it initially and it started at 0.00mm again. For the record, I don't like this. I'd much rather it start where the Z-offset is currently set since there is no way to check what the offset is from the printer screen. On the older firmware I was running, I could verify the value by running the calibration again, which was helpful. This was the main reason I had not updated to the newer firmware, in addition to the removal of the 'unload filament' button.

So I thought I would see if the value was stored under the 'baby steps' area in the config.mksini. There is a value there of 2.00, but that does not relate to any calibration value I have set for Z-offset. Nor does it change when I run the offset calibration and modify it greatly. I looked up where normal Klipper shows the Z-offset value, and it would have it stored in the 'Do Not Change' area at the bottom of the printer.cfg that is commented out. There is no value in my printer.cfg file either.

So, where is the Z-offset supposed to be stored with this version? Is there something broken with my install? Any help is greatly appreciated - this is the last thing I need to figure out before I can resume printing!

**Comment by RotorWash** [comment]
I just changed the value in config.mksini to 1.3. That fixed it. I have now changed it to the baby step value (cant remember, got machine in bits atm), and it now remembers the z value. But 1.3 is a good start.

**Comment by billkenney** [comment]
Glad you were able to get everything up and running. I'm not familiar with the cartographer setup, so I can't really speak to any of the specific settings or changes. 

But the z-offset is stored in config.mksini just like before. On my printer, before and after updating, it often forgot the z-offset when I set it on the screen. I ended up setting it to 0 and using fluidd to set the z-offset. Since doing that, it has never forgotten my z-offset. I think fluidd saves it in printer.cfg. 

You could try reinstalling firmware 4.3.13. ssh into your printer and run `mv ~/printer_data/config.mksini ~/printer_data/config.mksini.bak ; wget --no-check-certificate https://raw.githubusercontent.com/billkenney/qidi_3series_recovery/main/mksclient-max3.deb ; sudo dpkg -i mksclient-max3.deb`. Then delete klipper and moonraker and clone the repositories from GitHub. `cd /home/mks ; sudo rm -rf klipper moonraker ; git clone https://github.com/Klipper3d/klipper.git ; git clone https://github.com/Arksine/moonraker.git ; sudo service klipper restart ; sudo service moonraker restart`

I also added a new step 11 to my guide for updating the max3 printer/screen firmware to the latest 4.3.15. My screen firmware is still updating, but it seems like everything else is working okay.

**Comment by drewp29** [comment]
Bill - Thanks for the update instructions! I will bump up the 4.3.15 and see how it goes. Otherwise, as long as I can set the offset in some manner, everything else is golden. If that means setting it in Fluidd, that is fine, I just want to be able to reliably set it and be certain that it is the calibrated value. I'd rather not have to dial it in by printing a wide skirt on every print.

RotorWash - I am not sure what you are saying fixed it? Were you having the same issue?

**Comment by RotorWash** [comment]
Mine would forget its z height when it did its auto level at the start of a print. Thats how i fixed it. Even keeps the z height now after a restart.

**Comment by drewp29** [comment]
I'm attempting to install the 4.3.15 firmware per the guide and I am running into some errors.

When I run sudo dpkg -i mksclient-max3-4.3.15.deb here is what it returns:

(Reading database ... 112710 files and directories currently installed.)
Preparing to unpack mksclient-max3-4.3.15.deb ...
Unpacking makerbase-client (0.1.1) over (0.1.1) ...
dpkg: warning: unable to delete old directory '/home/mks/moonraker/moonraker/components/file_manager': Directory not empty
dpkg: warning: unable to delete old directory '/home/mks/moonraker/moonraker/components': Directory not empty
dpkg: warning: unable to delete old directory '/home/mks/moonraker/moonraker': Directory not empty
dpkg: warning: unable to delete old directory '/home/mks/moonraker': Directory not empty
dpkg: warning: unable to delete old directory '/home/mks/klipper/klippy/extras': Directory not empty
dpkg: warning: unable to delete old directory '/home/mks/klipper/klippy': Directory not empty
dpkg: warning: unable to delete old directory '/home/mks/klipper': Directory not empty
Setting up makerbase-client (0.1.1) ...
mv: cannot move '/root/config.mksini' to '/home/mks/klipper_config/config.mksini': No such file or directory
chmod: cannot access '/home/mks/klipper_config/config.mksini': No such file or directory
chown: cannot access '/home/mks/klipper_config/config.mksini': No such file or directory

The 'unable to delete' warnings I know are of no consequence, but the 'cannot move' and 'cannot access' errors I am not sure about. Are these going to keep things from installing correctly?

Looking at my file tree in MobaXterm is doesn't look like I have a klipper_config folder at all?

Thanks!

**Comment by drewp29** [comment]
So I proceeded past the errors I noted by just creating the klipper_config folder. Everything else installed fine, with the exception of klippain_shaketune.

The instructions say to reinstall klippain_shaketune by using the command: ~/klippain_shaketune/.install.sh

I had to remove the period in front of install to get it to work correctly. The install.sh file in the klippain_shaketune directory did not have the period in front of it, so I figured it may have been a typo in the guide.

Just waiting on the screen to install and then I will check everything is working per the guide, and its off to the races - hopefully!

I will report back if the newest firmware works as expected, or not.

**Comment by billkenney** [comment]
Thanks for the response. You can ignore all of these errors. So in my image klipper_config is just a link to printer_data, because qidi uses klipper_config but the recent versions of klipper use printer_data. Because we're still using qidi firmware, my simple solution was to create a link for the two folders. For some reason my klipper_config link was also deleted during the 4.3.15 firmware install. I wasn't aware that the firmware actually removed the link until your post, I thought I deleted it at some point. You can recreate the link by running `ln -s /home/mks/printer_data /home/mks/klipper_config`. I'll also update the klippain install command, the period was a typo.

**Comment by drewp29** [comment]
So far everything is working fine, but I still need to check the Z-offset stuff. Printer is heating up now.

I did however have a problem with timelapse: 

Moonraker has failed plugins, please check your logs, update your configuration and restart moonraker. 
timelapse Moonraker warnings found. Unparsed config section [timelapse] detected. This may be the result of a component that failed to load. In the future this will result in a startup error.

I do not currently have a webcam setup, though I want to get one eventually, so I did try to fix this by uninstalling and reinstalling timelapse, but was unsuccessful. Uninstall worked, but reinstall kept throwing errors, so I just commented out the timelapse areas in moonraker.conf and that seems to have solved it. I'll probably have to revisit this when I get a webcam installed.

**Comment by billkenney** [comment]
I've had the Timelapse issue before as well. The Timelapse link sometimes points to the wrong place. I've been able to get it working by rerunning the install script, i.e., `/home/mks/moonraker-timelapse/scripts/install.sh`. /home/mks/printer_data/config/timelapse.cfg should link to /home/mks/moonraker-timelapse/klipper_macro/timelapse.cfg. You can check the link location by running `ls -la ~/printer_data/config`. You should see this `timelapse.cfg -> /home/mks/moonraker-timelapse/klipper_macro/timelapse.cfg`. If it's linking to the wrong location, you can try `rm /home/mks/printer_data/config/timelapse.cfg ; ln -s /home/mks/moonraker-timelapse/klipper_macro/timelapse.cfg /home/mks/printer_data/config/timelapse.cfg`.

My date/time also got messed up with the firmware update. I updated the guide to fix the date/time and reinstall Timelapse. 

I think Timelapse also works with the [timelapse] section commented out. I wouldn't worry about it if the reinstall doesn't work.

**Comment by drewp29** [comment]
Yay! It appears everything is good! The Z-offset saves and actually shows it in Fluidd in the Tool section. And, what led me down this rabbit hole was initially the need for a 100% solid first layer on the entire build plate. I printed a 300x300mm single layer and dialed in the Z-offset and I can now say that I have a pretty good first layer overall. I still believe the way Klipper handles the ABL function could do with some tuning and perhaps a bit finer resolution of Z-height adjustment as there are still some thinner areas where the low spots are on the build surface. I am satisfied at this point that I will be able to keep a 320x320 print stuck for the estimated 21 hours, and that it will be laying down layers on an initial solid base.  

I will be printing speaker baffles for surround/ATMOS speakers that I am building and at 1.15kg of plastic per baffle (x8) I reeeeeaaally don't want to deal with any failed prints. I dealt with random failures on long prints for years with my previous printer, and I remember how frustrating it was to drop a print at the 20+ hour mark and have to start from scratch. No bueno.

I did reinstall timelapse because the printer started abnormally with an error regarding the missing timelapse configuration file, and rather than hunt down how to stop that, the reinstall allowed it to start without issue. Not sure if timelapse will work when I get around to installing a webcam, but for now it keeps it printing!

Thanks again for your help and time!

**Comment by billkenney** [comment]
No problem. If you really want to get your bed mesh dialed in...

https://www.klipper3d.org/Manual_Level.html#adjusting-bed-leveling-screws-using-the-bed-probe
Add your screw coordinates to screws_tilt_adjust in the printer.cfg, restart klipper, run G28 in the console, then run SCREWS_TILT_CALCULATE. The printer probes every corner of the bed and tells you how many turns to make. Make sure the build plate is on when you run the macro, or the nozzle could crash. Here are my settings for the max3:

[screws_tilt_adjust]
screw1: 6, 29
screw1_name: front left screw
screw2: 262, 29
screw2_name: front right screw
screw3: 262, 286
screw3_name: rear right screw
screw4: 6, 286
screw4_name: rear left screw
horizontal_move_z: 10
speed: 300
screw_thread: CCW-M4
