### ISSUE TITLE
Improve guide

### ISSUE THREAD

**Issue by MNTDVD** [billkenney/update_max3_plus3#12]
Hi and thanks for the great work!
Could you please improve the guide clearly dividing steps for each printer?
Don’t want to sound boring but it’s a complicated process and following a cleaner guide would be great!

thanks!

**Comment by billkenney** [comment]
Everything is identical except steps 7 and 8, and there are separate commands for each printer. I don't know how I could make the guide any clearer. If you want to make a suggestion I will consider it.
