### ISSUE TITLE
Some questions before starting on my x-Smart 3

### ISSUE THREAD

**Issue by theclue** [billkenney/update_max3_plus3#13]
First of all, tnx allot for your effort writing this WONDERFUL guide. Having to replace the built-in screen was always blocking me to start the journey. Now I have no excuses.

But first I've a couple of questions, just to be sure I won't miss something.

1. I'm going to buy an eMMC/32Gb for the fresh install, as I will keep the original 8gb as backup (let alone is not big enough anyway). Any eMMC will be ok or shall I buy the official QIDI one (it doesn't seem special, actually, but who know?). Which eMMC do you reccommend, if any?

2. Same for the eMMC/USB3 adapter. Any one would be ok?

3. About the toolhead flashing, is it usually safe or I should need a spare one in case a revert is needed? (I would avoid it actually, it's not exactly cheap, looks like a waste of money to me)

4. Technically speaking, x-Smart doesn't have LAN, but in facts the board has one. Is it working out of the boc? (I guess I would need an usb-to-lan if not)

5. I was wondering if your image will put the printer on the official klipper release streams or you just one-shot update the special QIDI/klipper fork. Ie, after the procedure is done, one can in future safely upgrade klipper using kihaut? I would definitively kill that stupid klipper fork forever, if I can and start using more klipper plugins finally *hungry*

6. Since the x-Smart firmware must be reinstalled to keep the screen working, which is the latest one that I should have? This because official updates streams are definitivelt not reliable, those days and I'm not sure I'm in sync. Is it safe to apply che 7-8 steps anyway if not sure?

7. I have one centralized Spoolman install on a remote machine to manage my entire 3d printer fleets, is it easy to disable your embedded one after install to point klipper to my existing one?

8. Before mounting and flashing the toolhead do I have to unplug all the other usb devices? What about the screen?

9. I was wondering if this guide will also open to the possibility to customize the UI for the screen...I have some ideas....

If I'll be able to do the procedure, I'll be happy to contrib in sharing the experience or writing some specific tutorials for the x-Smart if this could be helpful :)

**Comment by billkenney** [comment]
> I'm going to buy an eMMC/32Gb for the fresh install, as I will keep the original 8gb as backup (let alone is not big enough anyway). Any eMMC will be ok or shall I buy the official QIDI one (it doesn't seem special, actually, but who know?). Which eMMC do you reccommend, if any?
>
> Same for the eMMC/USB3 adapter. Any one would be ok?

Just buy the Qidi emmc, it comes with the adapter. 

> About the toolhead flashing, is it usually safe or I should need a spare one in case a revert is needed? (I would avoid it actually, it's not exactly cheap, looks like a waste of money to me)

You don't need a spare toolhead. You can flash it back to 0.10 if you want to revert the software. 

> Technically speaking, x-Smart doesn't have LAN, but in facts the board has one. Is it working out of the boc? (I guess I would need an usb-to-lan if not)

Currently you need LAN to connect to the internet so you can ssh into your printer. If the smart3 doesn't have LAN, you should get a USB adapter. After the initial setup you can use WiFi. 

> I was wondering if your image will put the printer on the official klipper release streams or you just one-shot update the special QIDI/klipper fork. Ie, after the procedure is done, one can in future safely upgrade klipper using kihaut? I would definitively kill that stupid klipper fork forever, if I can and start using more klipper plugins finally hungry

It's the official klipper/moonraker/fluidd release. You can update anytime and use whatever plugins you want. 

> Since the x-Smart firmware must be reinstalled to keep the screen working, which is the latest one that I should have? This because official updates streams are definitivelt not reliable, those days and I'm not sure I'm in sync. Is it safe to apply che 7-8 steps anyway if not sure?

Just install the firmware from my repository. It has the latest firmware for all three printers. Yes you can always reinstall the firmware if you're not sure what version you have installed. 

> I have one centralized Spoolman install on a remote machine to manage my entire 3d printer fleets, is it easy to disable your embedded one after install to point klipper to my existing one?

To disable spoolman on the printer just run `sudo systemctl Spoolman disable`

> Before mounting and flashing the toolhead do I have to unplug all the other usb devices? What about the screen?

No you do not have to unplug the screen. Just the other usb devices on the mainboard. 

> I was wondering if this guide will also open to the possibility to customize the UI for the screen...I have some ideas....

There's actually a different version of the screen firmware you can install. I'm using it now and it works well. It also makes it unnecessary to install any of the Qidi firmware, which is great. I'm planning on linking to it in my guide at some point. 
https://github.com/Phil1988/FreeDi

**Comment by theclue** [comment]
Tnx allot! I'm going to start the conversion this weekend!

Weird enough, I discovered that the x-Smart shares the same control board of the bigger brothers.

Thus, it *has* a LAN socket on board, just not ported to the chassis. With an easy patch chord and a beveled cut-out, now the printer has a wired ethernet as well :D

**Comment by billkenney** [comment]
That's great...although it makes zero sense that Qidi didn't add an external connection to the LAN port. Let me know if you run into any issues, or if you successfully update. I haven't gotten any feedback from Smart3 users yet
