### ISSUE TITLE
Klipperscreen upgrade

### ISSUE THREAD

**Issue by qpens** [billkenney/update_max3_plus3#14]
Hi,

Is there any chance to add option of removing original screen services for people who want use your IMG but with Klipperscreen?

**Comment by billkenney** [comment]
You can disable whatever services you want, but I'm pretty sure klipperscreen doesn't work with the Qidi screens.

**Comment by qpens** [comment]
I replaced the screen. The only thing is the time of booting printer. Will printer boot faster after switching off service responsible for qidi screen if yes what is the command?

**Comment by billkenney** [comment]
`sudo systemctl stop makerbase-client.service ; sudo systemctl disable makerbase-client.service`

It likely will not boot faster. If you want to re-enable the service: `sudo systemctl enable makerbase-client.service`
