### ISSUE TITLE
Step 10 in https://github.com/billkenney/update_max3_plus3/blob/main/manual.md

### ISSUE THREAD

**Issue by cptcl** [billkenney/update_max3_plus3#2]
Hello again. Tryed youzr Guide again, cause i could not sleep well without getting it done.
I know why its not working, at least i think.  just i dont know so much about coding and scripting.

In step 10 it says i should 
``` wget https://raw.githubusercontent.com/billkenney/max3_plus3_recovery/main/mksclient-max3.deb ; wget https://raw.githubusercontent.com/billkenney/max3_plus3_recovery/main/800_480.tft ; sudo dpkg -i mksclient-max3.deb ; sudo mv 800_480.tft /root ```
so if i run ``` sudo dpkg -i mksclient-max3.deb ``` i already told u that it doesnt work and i get a "Command not found" error.
I found out that python is working but it throws an error in /root/merge.py in row 3

Its because we use python3 and i found this ``` In Python 3, [ConfigParser](https://docs.python.org/2/library/configparser.html) has been renamed to [configparser](https://docs.python.org/3/library/configparser.html) for PEP 8 compliance. It looks like the package you are installing does not support Python 3. ``` 

So in the /root/merge.py all commands are "ConfigParser" and not "configparser"
Maybe thats why it didnt work? 
How can i solve this?
I would really like try your solution, but again, not only copy pasta :D

EDIT:
No error when ``` sudo apt-get install python-is-python3 ``` and ``` sudo cp /usr/lib/python3.11/configparser.py /usr/lib/python3.11/ConfigParser.py ``` 
now i do the next steps..

EDIT2: ``` cd /home/mks/rtl8xxxu ; sudo modprobe rtl8xxxu_git ``` does not work. it says ``` modprobe: ERROR: could not insert 'rtl8xxxu_git': Invalid argument ```  

EDIT3: Rerun step 16 again and now no error message

And for now... Everything seems to work. Will drive a testprint now.

**Comment by billkenney** [comment]
I had the configparser error as well. I tried to find a solution but and was unable to get the merge.py script to work. I'll add your fix to the guide. 

Glad that you were able to get everything working though!

**Comment by cptcl** [comment]
Atm i in the calibration phase. I hope everything works. :D will print something in about 30 min
I mean.. at some point (if qidi quits to make updated) i guess u cant get another way around than to install another display. Or u think we can use this methode in your guide forever? at some point i guess even this files where then too old. Did u think about an option to update if klipper gets another update? or do we need to start over from the beginning with the guide?

**Comment by cptcl** [comment]
Resonance test
```  17:51:17  !! Failed to import `numpy` module, make sure it was installed via `~/klippy-env/bin/pip install` (refer to docs/Measuring_Resonances.md for more details).
17:51:17  !! Failed to import `numpy` module, make sure it was installed via `~/klippy-env/bin/pip install` (refer to docs/Measuring_Resonances.md for more details).
17:51:17  !! Failed to import `numpy` module, make sure it was installed via `~/klippy-env/bin/pip install` (refer to docs/Measuring_Resonances.md for more details). ```

**Comment by billkenney** [comment]
Now that you have the makerbase-client / xindi service running, that's all you need for a working screen. You can update klipper, moonraker, fluidd, etc at any time. I just updated klipper and moonraker and my screen still works. If you did install the qidi patch files, you need to install those again every time you update. 
![Screen Shot 2024-05-25 at 10 46 21 AM](https://github.com/billkenney/update_max3_plus3/assets/30010560/3efc2da7-33e0-44e1-afc3-6d9719a756d6)
![Screen Shot 2024-05-25 at 10 48 44 AM](https://github.com/billkenney/update_max3_plus3/assets/30010560/d64dd07d-bf31-45b7-b573-b867a24311e2)

**Comment by cptcl** [comment]
> Resonance test `` 17:51:17 !! Failed to import `numpy` module, make sure it was installed via `~/klippy-env/bin/pip install` (refer to docs/Measuring_Resonances.md for more details). 17:51:17 !! Failed to import `numpy` module, make sure it was installed via `~/klippy-env/bin/pip install` (refer to docs/Measuring_Resonances.md for more details). 17:51:17 !! Failed to import `numpy` module, make sure it was installed via `~/klippy-env/bin/pip install` (refer to docs/Measuring_Resonances.md for more details). ``

do you think i should go and install it like here? ``` https://github.com/Klipper3d/klipper/blob/master/docs/Measuring_Resonances.md#software-installation ``` 

also thanks for this info. and... system upgrade (13) should not be done right?

**Comment by billkenney** [comment]
> Resonance test `` 17:51:17 !! Failed to import `numpy` module, make sure it was installed via `~/klippy-env/bin/pip install` (refer to docs/Measuring_Resonances.md for more details). 17:51:17 !! Failed to import `numpy` module, make sure it was installed via `~/klippy-env/bin/pip install` (refer to docs/Measuring_Resonances.md for more details). 17:51:17 !! Failed to import `numpy` module, make sure it was installed via `~/klippy-env/bin/pip install` (refer to docs/Measuring_Resonances.md for more details). ``

I haven't tried the resonance test. Seems like you need to install numpy in the klipper virtual environment. `source ~/klippy-env/bin/activate ; pip install numpy ; deactivate`

**Comment by cptcl** [comment]
> > Resonance test `` 17:51:17 !! Failed to import `numpy` module, make sure it was installed via `~/klippy-env/bin/pip install` (refer to docs/Measuring_Resonances.md for more details). 17:51:17 !! Failed to import `numpy` module, make sure it was installed via `~/klippy-env/bin/pip install` (refer to docs/Measuring_Resonances.md for more details). 17:51:17 !! Failed to import `numpy` module, make sure it was installed via `~/klippy-env/bin/pip install` (refer to docs/Measuring_Resonances.md for more details). ``
> 
> I haven't tried the resonance test. Seems like you need to install numpy in the klipper virtual environment. `source ~/klippy-env/bin/activate ; pip install numpy ; deactivate`

Did what de docs said

Note that resonance measurements and shaper auto-calibration require additional software dependencies not installed by default. First, run on your Raspberry Pi the following commands:

``` 
sudo apt update
sudo apt install python3-numpy python3-matplotlib libatlas-base-dev libopenblas-dev 
``` 

Next, in order to install NumPy in the Klipper environment, run the command:

``` 
~/klippy-env/bin/pip install -v numpy
 ``` 

Note that, depending on the performance of the CPU, it may take a lot of time, up to 10-20 minutes. Be patient and wait for the completion of the installation. On some occasions, if the board has too little RAM the installation may fail and you will need to enable swap.

And it works. Resonance test is crucial for me

**Comment by cptcl** [comment]
Hm... I can upload from qidi slicer or orcaslicer ,.. but not print.

HTTP 500: {"error": {"code": 500, "message": "Internal Server Error", "traceback": "Traceback (most recent call last):\n\n File \"/home/mks/moonraker-env/lib/python3.11/site-packages/tornado/web.py\", line 1790, in _execute\n result = await result\n ^^^^^^^^^^^^\n\n File \"/home/mks/moonraker/moonraker/components/application.py\", line 1019, in post\n result = await self.file_manager.finalize_upload(form_args)\n ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\n File \"/home/mks/moonraker/moonraker/components/file_manager/file_manager.py\", line 825, in finalize_upload\n result = await self._finish_gcode_upload(upload_info)\n ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\n File \"/home/mks/moonraker/moonraker/components/file_manager/file_manager.py\", line 910, in _finish_gcode_upload\n await kapis.start_print(upload_info['filename'], user=user)\n ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\nTypeError: KlippyAPI.start_print() got an unexpected keyword argument 'user'\n"}}

U have an idea?

**Comment by billkenney** [comment]
I have no idea. Maybe try reinstalling klipper and moonraker? I've never had an error like that with or a or Qidi slicer.

**Comment by cptcl** [comment]
Did step 14. Removed klipper & moonraker, then installed it again with qidi patches. 
Same result. OMG im so near to get it done....
Try it again without qidi patches.. see if there is a problem

EDIT: without qidi patches it works. But display then only shows the start screen.

**Comment by billkenney** [comment]
> Did step 14. Removed klipper & moonraker, then installed it again with qidi patches. Same result. OMG im so near to get it done.... Try it again without qidi patches.. see if there is a problem
> 
> EDIT: without qidi patches it works. But display then only shows the start screen.

My display shows the same screen it usually does when you start a print, but it doesn't show a preview of the stl. Maybe try initiating the print from the printer screen and see if it shows the print screen. 

Glad you got it working though! Is there anything else in my guide that I should change or add?

**Comment by cptcl** [comment]
Yeah.. sadly the best thing about the qidi display is.. useablility (has good menu and big up and down buttons. Klipperscreen does often a double klick or a klick when i scroll, and the up and down buttons are like non hitable) 
Than on qidi display u can see what filament type it is.. that i have not found on klipperscreen. Wenn u hit a print on klipperscreen u will see just the name and an image. nothing else.. if u forgot to put the filament type u used in the name ur screwd.
Thats why i wanted to use the original display so hard. i think i will try and fiddle a bit around.
Didi u include numpy installation in the guide? and the ConfigParser thing?

**Comment by billkenney** [comment]
> Didi u include numpy installation in the guide? and the ConfigParser thing?

Added it to the end. I have klippain-shake time on my printer, I'll have to compare the results with the klipper macro.

**Comment by billkenney** [comment]
> also thanks for this info. and... system upgrade (13) should not be done right?

I did the system update. I think it just runs `sudo apt update ; sudo apt upgrade -y` which i manually run every month or so to keep all of the other packages up to date. The kernel headers and some other stuff will not update so it can't really break the system.
