### ISSUE TITLE
Maybe worth to note a few things again..

### ISSUE THREAD

**Issue by cptcl** [billkenney/update_max3_plus3#3]
Hi.. its me again.
So a few things i noticed since yesterday.

1.  If u dont use the qidi patch files, u cant rly use qidi slicer, cause moonraker will not identify qidi slicer (in patchfiles the qidi slicer will get recognized as a qidi prusa slicer.) Without these patchfiles u will only see the name of the gcode generated by qidi slicer. Nothing else! But Orcaslicer and Prusaslicer works.
2. If u have a modified printbed with rotary wheels like me and need to use the macro, than dont put it in printer.cfg. Your display will show "System starts abnomally". Put it in the macros.cfg and it will work. Thats why i had problems here PS: Yes now i have all qidi patches applied and printer works like yours just without thumbnails on the printer itself
``` 
[screws_tilt_adjust]
screw1: 5, 30
screw1_name: vorne links
screw2: 260, 30
screw2_name: vorne rechts
screw3: 260, 285
screw3_name: hinten rechts
screw4: 5, 285
screw4_name: hinten links
horizontal_move_z: 10
speed: 50
screw_thread: CW-M4 
```  
... will look around for thumbnail thing..

**Comment by billkenney** [comment]
> 1.  If u dont use the qidi patch files, u cant rly use qidi slicer, cause moonraker will not identify qidi slicer (in patchfiles the qidi slicer will get recognized as a qidi prusa slicer.) Without these patchfiles u will only see the name of the gcode generated by qidi slicer. Nothing else! But Orcaslicer and Prusaslicer works.

I don't have the patch files installed and I use Qidi slicer. And I can upload to the printer and print from the screen, or 'upload and print' and have never had a problem. I don't understand why you're saying it doesn't work?

**Comment by cptcl** [comment]
Than why using/mention these files anyway if they dont work? if they dont make any difference. My main point is, that i can still use this display.

**Comment by billkenney** [comment]
> Than why using/mention these files anyway if they dont work? if they dont make any difference. My main point is, that i can still use this display. 

Because Qidi is the manufacturer and they write an update guide including patch files. I state in the guide that they are unnecessary and that I think they only make thumbnails work. But they are from the manufacturer and I thought I should give people the option to install them if they want to.

**Comment by billkenney** [comment]
> screw_thread: CW-M4 

This should be CCW-M4 btw

**Comment by cptcl** [comment]
> > screw_thread: CW-M4
> 
> This should be CCW-M4 btw

no. its CW for me. i dont use the original screws

For the qidi patches... it seems they dont work anymore. at least we know that u can delete the qidi patches from your guide. Cause they do nothing.

**Comment by billkenney** [comment]
> For the qidi patches... it seems they dont work anymore. at least we know that u can delete the qidi patches from your guide. Cause they do nothing.

I made it much more clear that the patch files are not necessary and the installation is not recommended.

**Comment by cptcl** [comment]
i dont blame u. Was my fault. Just wanted to help here.
