### ISSUE TITLE
The system starts abnormally

### ISSUE THREAD

**Issue by riegaz** [billkenney/update_max3_plus3#4]
Hi there,

I followed your guide step by step and everything ran through without an issue. After running step 10 and restarting, I get the "the system starts abnormally message.

Any help is welcome.

**Comment by riegaz** [comment]
So after moving the kipper.uf2 again it boots normally now. Thus, I will close this issue.

**Comment by billkenney** [comment]
> So after moving the kipper.uf2 again it boots normally now. Thus, I will close this issue.

I added a note in the guide to flash the extruder mcu again if you get the system starts abnormally error
