### ISSUE TITLE
wlan0 is missing

### ISSUE THREAD

**Issue by qpens** [billkenney/update_max3_plus3#7]
After update wifi stoped working wlan0 is missing. lsusb shows that device is connected

**Comment by billkenney** [comment]
The WiFi doesn't work on the screen after the update. You can ssh into your printer run `sudo nmtui` and configure WiFi settings there. If that doesn't work,

ssh into your printer and run `sudo ln -s /usr/src/linux-headers-6.7.5-edge-rockchip64/arch/arm64 /usr/src/linux-headers-6.7.5-edge-rockchip64/arch/aarch64 ; sudo apt install make gcc build-essential git network-manager ; cd /home/mks ; git clone https://github.com/lwfinger/rtl8xxxu ; cd /home/mks/rtl8xxxu ; make clean modules ; sudo make install ; sudo make install_fw`

Restart the printer, then: `cd /home/mks/rtl8xxxu ; sudo modprobe rtl8xxxu_git`

you can run sudo nmtui to use the network-manager service to create or manage network connections. if you get any errors, run `cd /home/mks/rtl8xxxu ; make clean modules ; sudo make install ; sudo make install_fw`, reboot, and run `cd /home/mks/rtl8xxxu ; sudo modprobe rtl8xxxu_git` again

**Comment by billkenney** [comment]
You can also try the fix from this issue to change the wifi name to wlan0 https://github.com/billkenney/update_max3_plus3/issues/6:
`sudo printf 'ACTION=="add", SUBSYSTEM=="net", KERNEL=="wlan0", NAME="wlan0"' > /etc/udev/rules.d/70-custom-names.rules ; udevadm control --reload-rules ; sudo reboot`

**Comment by billkenney** [comment]
This is fixed in the latest release
