### ISSUE TITLE
kliper lost connection

### ISSUE THREAD

**Issue by qpens** [billkenney/update_max3_plus3#8]
Hi,

Im not sure if the klipper connection problem is related to step 6 that I cant fully execute.. Im geting error after comands:
rm ~/klipper_config/config/MKS_THR.cfg ; ln -s ~/klipper_config/MKS_THR.cfg ~/klipper_config/config/MKS_THR.cfg

Command 'rm' is available in the following places
 * /bin/rm
 * /usr/bin/rm
The command could not be located because '/usr/bin:/bin' is not included in the PATH environment variable.
rm: command not found
Command 'ln' is available in the following places
 * /bin/ln
 * /usr/bin/ln
The command could not be located because '/bin:/usr/bin' is not included in the PATH environment variable.
ln: command not found

In printer klipper just show Klipper state: Disconnect

**Comment by qpens** [comment]
Ok , so I found the problem. I'm using induction probe and installing any probe or patch probe config is disconnecting Klipper going back to BL touch config the kipper is working fine. Any chance for getting fix for probe printer config?

**Comment by billkenney** [comment]
That error wouldn't have anything to do with the printer.cfg, it means there's a problem with the environment. If something like this happens again you can try running `exec zsh` to reset the environment, or restart the printer. 

These are the only differences between the printer.cfg for the bltouch and the inductive probe. You can try editing the file yourself and making these changes and see if that works. The G1 section needs to be changed in 2 places

Bltouch

G1 X{printer.toolhead.axis_maximum.x/2 - printer.configfile.settings.bltouch.x_offset} Y{printer.toolhead.axis_maximum.y/2 - printer.configfile.settings.bltouch.y_offset} F7800

[bltouch]
sensor_pin:^MKS_THR:gpio21
control_pin:MKS_THR:gpio11
stow_on_each_sample: False
#[probe]
#pin: ^!MKS_THR:gpio21
x_offset: 28
y_offset: 4.4
z_offset: 0.0
speed: 5
samples: 2
samples_result: average
sample_retract_dist: 3.0
samples_tolerance: 0.08
samples_tolerance_retries:3

Probe

G1 X{printer.toolhead.axis_maximum.x/2 - printer.configfile.settings.probe.x_offset} Y{printer.toolhead.axis_maximum.y/2 - printer.configfile.settings.probe.y_offset} F7800

#[bltouch]
#sensor_pin:^MKS_THR:gpio21
#control_pin:MKS_THR:gpio11
#stow_on_each_sample: False
[probe]
pin: ^!MKS_THR:gpio21
x_offset: 28
y_offset: 4.4
z_offset: 0.0
speed: 5
samples: 2
samples_result: average
sample_retract_dist: 3.0
samples_tolerance: 0.08
samples_tolerance_retries:3

**Comment by qpens** [comment]
Yesterday I did step by step your instalation  guide and I got error : Include file '/home/mks/printer_data/config/Adaptive_Mesh.cfg' does not exist 

what worked for me is removing line [include Adaptive_Mesh.cfg] from printer.cfg.
Printer is working ok now.

**Comment by billkenney** [comment]
The current image uses KAMP instead of the Adaptive_Mesh file. I must've forgotten to remove that line from the printer.cfg files. They have been updated, so it shouldn't be a problem in the future. Thanks for the post!

**Comment by billkenney** [comment]
I also noticed something else was missing from the printer.cfg files. Add this to your printer.cfg as well.

[include macros.cfg]
