### ISSUE TITLE
Error at Part 6

### ISSUE THREAD

**Issue by freneter** [billkenney/update_max3_plus3#9]
Part 6 is the end for me.
![Screenshot 2024-09-28 163148](https://github.com/user-attachments/assets/eeb97d61-047f-4556-a3dd-bd7b6b150fd8)

**Comment by billkenney** [comment]
Try `exec zsh` then run the command again. Or restart your printer and run the command again. Or restart your printer and skip this step. If you get an error about not recognizing an MCU after finishing the rest of the guide, try this step again.

**Comment by billkenney** [comment]
Command 6 has been updated and the errors no longer occur. For some reason, the printf command was causing the printer environment to go haywire.
